hwi_oauth:
    resource_owners:
        google:
            type:                google
            client_id:           '%env(GOOGLE_CLIENT_ID)%'
            client_secret:       '%env(GOOGLE_CLIENT_SECRET)%'
            scope:               "email profile"
