security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        users_in_memory: { memory: null }
        hwi_provider:
            id: hwi_oauth.user.provider

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
                    lazy: true

                    # Define the path handling the logout and where to redirect
                    logout:
                        path: /logout
                        target: /

                    oauth:
                        # Again, define the same path as in the Google Cloud Console
                        resource_owners:
                            google: "/login/with-google"
                        # This is the route that will trigger the OAuth login process
                        login_path: /connect/google
                        use_forward: false
                        failure_path: /login

                        # Service defined in HWI OAuth bundle to handle OAuth
                        oauth_user_provider:
                            service: hwi_oauth.user.provider

                    # Key of the provider defined earlier
                    provider: hwi_provider

            # Activate different ways to authenticate:
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Note: Only the *first* matching rule is applied
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        ## /login/with-google
        ## /login
        - { path: ^/google_access_token, role: PUBLIC_ACCESS}
        - { path: ^/login, roles: PUBLIC_ACCESS}
        - { path: ^/login/with-google, roles: PUBLIC_ACCESS}
        - { path: ^/connect/google, roles: PUBLIC_ACCESS}
        - { path: ^/api/doc, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER }
        # - { path: ^/(.+), roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
